create or replace function public.item_json(i public.wardrobe_items) returns jsonb language sql immutable as $$
select jsonb_build_object('id',i.id,'userId',i.owner_id,'name',i.name,'brand',i.brand,'category',i.category,'season',i.season,'length',i.length,'topType',i.top_type,'accessoryType',i.accessory_type,'rating',i.rating,'story',i.story,'purchaseYear',i.purchase_year,'imageUrl',i.image_url,'orderIndex',i.order_index,'shared',i.shared,'createdAt',extract(epoch from i.created_at)*1000,'updatedAt',extract(epoch from i.updated_at)*1000)
$$;
create or replace function public.match_json(m public.best_matches) returns jsonb language sql immutable as $$
select jsonb_build_object('id',m.id,'userId',m.owner_id,'items',m.items,'allItemIds',m.all_item_ids,'name',m.name,'story',m.story,'sceneTags',m.scene_tags,'photoBase64',m.photo_url,'shared',m.shared,'createdAt',extract(epoch from m.created_at)*1000,'updatedAt',extract(epoch from m.updated_at)*1000)
$$;

create or replace function public.get_public_wardrobe(p_public_id text, p_limit integer default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare p profiles; result jsonb;
begin select * into p from profiles where public_id=p_public_id; if p.id is null or not p.wardrobe_public then return null; end if;
select jsonb_build_object('wardrobePublic',true,'items',coalesce((select jsonb_agg(item_json(i) order by i.created_at desc) from (select * from wardrobe_items where owner_id=p.id order by created_at desc limit case when p_limit is null then 2147483647 else p_limit end) i),'[]'::jsonb),'matches',case when p_limit is null then coalesce((select jsonb_agg(match_json(m) order by m.created_at desc) from best_matches m where owner_id=p.id),'[]'::jsonb) else '[]'::jsonb end) into result; return result; end $$;
create or replace function public.get_public_item(p_public_id text,p_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare p profiles;i wardrobe_items; begin select * into p from profiles where public_id=p_public_id; select * into i from wardrobe_items where id=p_id and owner_id=p.id; if i.id is null or not(i.shared or p.wardrobe_public) then return null; end if; return item_json(i); end $$;
create or replace function public.get_public_match(p_public_id text,p_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare p profiles;m best_matches; begin select * into p from profiles where public_id=p_public_id; select * into m from best_matches where id=p_id and owner_id=p.id; if m.id is null or not(m.shared or p.wardrobe_public) then return null; end if; return jsonb_build_object('match',match_json(m),'items',coalesce((select jsonb_agg(item_json(i)) from wardrobe_items i where i.owner_id=p.id and i.id=any(m.all_item_ids)),'[]'::jsonb)); end $$;

create or replace function public.consume_ai_import(p_max integer default 40,p_window_ms bigint default 3600000) returns boolean language plpgsql security definer set search_path=public as $$ declare u uuid:=auth.uid(); now_ms bigint:=(extract(epoch from clock_timestamp())*1000)::bigint; r ai_import_usage; begin if u is null then raise exception 'unauthorized'; end if; select * into r from ai_import_usage where owner_id=u for update; if r.owner_id is null or now_ms-r.window_start>=p_window_ms then insert into ai_import_usage(owner_id,window_start,count) values(u,now_ms,1) on conflict(owner_id) do update set window_start=excluded.window_start,count=1; return false; end if; if r.count>=p_max then return true; end if; update ai_import_usage set count=count+1 where owner_id=u; return false; end $$;

grant execute on function public.get_public_wardrobe(text,integer),public.get_public_item(text,text),public.get_public_match(text,text) to anon,authenticated;
grant execute on function public.consume_ai_import(integer,bigint) to authenticated;
revoke execute on function public.consume_ai_import(integer,bigint) from anon;
